// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parser.Data;

namespace parser.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201027041629_Add Rubric")]
    partial class AddRubric
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("parser.Models.Rubric", b =>
                {
                    b.Property<string>("RubricId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("RubricId");

                    b.ToTable("Rubrics");
                });
#pragma warning restore 612, 618
        }
    }
}
